default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  username: remote
  password: 067dcea2cf57
  host: server.madgrades.com
  port: 3306
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: madgrades

test:
  <<: *default
  database: madgrades_test

production:
  <<: *default
  database: madgrades
